# Generated by Django 3.2.16 on 2022-10-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OFA', '0002_remove_ofaimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofaimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
