# Generated by Django 3.2.16 on 2022-10-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OFA', '0003_alter_ofaimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofaimage',
            name='image',
            field=models.ImageField(upload_to='OFA\\static'),
        ),
    ]
